import { registrarTextos } from '../shared/i18n.js';

registrarTextos('es', {
  bienvenida: 'Te damos la bienvenida a',
  titulo_portada: 'Descubre nuestro menú',
  comenzar: 'Comenzar',
  ayuda_portada: 'Toca la pantalla para explorar',
  idioma_es: 'ESP',
  idioma_en: 'ENG',
  idioma_etiqueta: 'Idioma',
  error_config_titulo: 'Este kiosco no está configurado',
  error_config_detalle: 'Avisa al personal para continuar.',
  ident_titulo_1: 'Por favor,',
  ident_titulo_2: 'ingresa tus datos',
  campo_edificio: 'Edificio',
  campo_habitacion: 'Habitación',
  campo_nombre: 'Confirma tu nombre',
  reserva_a_nombre: 'Reserva a nombre de',
  continuar: 'Continuar',
  verificando: 'Verificando…',
  verificando_lento: 'Esto puede tardar unos segundos…',
  no_soy_yo: 'No soy yo',
  teclado_borrar: 'Borrar',
  teclado_listo: 'Listo',
  err_no_coincide: 'Edificio o habitación no coinciden. Revisa tus datos e inténtalo de nuevo.',
  err_bloqueado: 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.',
  err_red: 'No pudimos conectarnos. Inténtalo de nuevo.',
  err_general: 'Algo salió mal. Avisa al personal.',
  volver: 'Volver',
  menu_titulo: 'Menú',
  menu_cargando: 'Preparando el menú…',
  menu_error: 'No pudimos cargar el menú. Inténtalo de nuevo.',
  reintentar: 'Reintentar',
  agotado: 'Agotado',
  agregar: 'Agregar',
  orden_aria: 'Mi orden',
  aviso_max_producto: 'Llegaste al máximo de este platillo.',
  aviso_max_total: 'Llegaste al máximo de artículos por pedido.'
});

registrarTextos('en', {
  bienvenida: 'Welcome to',
  titulo_portada: 'Discover our menu',
  comenzar: 'Start',
  ayuda_portada: 'Tap the screen to explore',
  idioma_es: 'ESP',
  idioma_en: 'ENG',
  idioma_etiqueta: 'Language',
  error_config_titulo: 'This kiosk is not set up',
  error_config_detalle: 'Please let a team member know.',
  ident_titulo_1: 'Please,',
  ident_titulo_2: 'enter your details',
  campo_edificio: 'Building',
  campo_habitacion: 'Room',
  campo_nombre: 'Confirm your name',
  reserva_a_nombre: 'Booked under',
  continuar: 'Continue',
  verificando: 'Checking…',
  verificando_lento: 'This may take a few seconds…',
  no_soy_yo: "That's not me",
  teclado_borrar: 'Delete',
  teclado_listo: 'Done',
  err_no_coincide: "Building and room don't match. Please check your details and try again.",
  err_bloqueado: 'Too many attempts. Please wait a minute and try again.',
  err_red: "We couldn't connect. Please try again.",
  err_general: 'Something went wrong. Please let a team member know.',
  volver: 'Back',
  menu_titulo: 'Menu',
  menu_cargando: 'Preparing the menu…',
  menu_error: "We couldn't load the menu. Please try again.",
  reintentar: 'Try again',
  agotado: 'Sold out',
  agregar: 'Add',
  orden_aria: 'My order',
  aviso_max_producto: "You've reached the maximum for this dish.",
  aviso_max_total: "You've reached the maximum items per order."
});