import { registrarTextos } from '../shared/i18n.js';

registrarTextos('es', {
  bienvenida: 'Te damos la bienvenida a',
  titulo_portada: 'Descubre nuestro menú',
  comenzar: 'Comenzar',
  ayuda_portada: 'Toca la pantalla para explorar',
  idioma_es: 'ESP',
  idioma_en: 'ENG',
  idioma_etiqueta: 'Idioma',
  error_config_titulo: 'Este kiosco no está configurado',
  error_config_detalle: 'Avisa al personal para continuar.',
  ident_titulo_1: 'Por favor,',
  ident_titulo_2: 'ingresa tus datos',
  campo_edificio: 'Edificio',
  campo_habitacion: 'Habitación',
  campo_nombre: 'Confirma tu nombre',
  reserva_a_nombre: 'Reserva a nombre de',
  continuar: 'Continuar',
  verificando: 'Verificando…',
  verificando_lento: 'Esto puede tardar unos segundos…',
  no_soy_yo: 'No soy yo',
  teclado_borrar: 'Borrar',
  teclado_listo: 'Listo',
  err_no_coincide: 'Edificio o habitación no coinciden. Revisa tus datos e inténtalo de nuevo.',
  err_bloqueado: 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.',
  err_red: 'No pudimos conectarnos. Inténtalo de nuevo.',
  err_general: 'Algo salió mal. Avisa al personal.',
  volver: 'Volver',
  menu_titulo: 'Menú',
  menu_cargando: 'Preparando el menú…',
  menu_error: 'No pudimos cargar el menú. Inténtalo de nuevo.',
  reintentar: 'Reintentar',
  agotado: 'Agotado',
  agregar: 'Agregar',
  orden_aria: 'Mi orden',
  aviso_max_producto: 'Llegaste al máximo de este platillo.',
  aviso_max_total: 'Llegaste al máximo de artículos por pedido.',
  ordenar: 'Ordenar',
  ver_detalle: 'Ver detalle de',
  aviso_agregado: 'agregado a tu orden',
  menu_lento: 'Esto está tardando más de lo normal. Por favor espera…',
  aviso_agotado: 'Este platillo está agotado por ahora.',
  orden_titulo: 'Confirma tu orden:',
  orden_producto: 'Producto',
  orden_cantidad: 'Cantidad',
  orden_vacia: 'Tu orden está vacía.',
  orden_quitar: 'Quitar',
  orden_cantidad_aria: 'Cantidad de',
  aviso_max_lineas: 'Llegaste al máximo de platillos distintos por pedido.',
  enviando: 'Enviando…',
  pedido_lento: 'Esto está tardando un poco. Tu pedido sigue en proceso, por favor espera.',
  pedido_stock: 'Ajustamos tu orden por disponibilidad:',
  pedido_stock_reintento: 'Cambió la disponibilidad de algunos platillos. Inténtalo de nuevo.',
  pedido_huesped: 'No pudimos validar tu habitación. Avisa al personal.',
  pedido_rate: 'Hay muchas solicitudes. Espera un momento e inténtalo de nuevo.',
  ticket_titulo_1: 'Tu pedido',
  ticket_titulo_2: 'es el número:',
  ticket_mensaje: 'Por favor, revisa la pantalla “Estado de pedidos” para avisarte cuando esté listo.',
  ticket_gracias: '¡Gracias!',
  ticket_finalizar: 'Finalizar pedido',
  inactividad_titulo: '¿Sigues ahí?',
  inactividad_pedido: 'Tu pedido se cancelará en',
  inactividad_sesion: 'La sesión se cerrará en',
  inactividad_segundos: 'segundos',
  inactividad_seguir: 'Seguir aquí',
  espera_etiqueta: 'Estado de pedidos',
  espera_etiqueta_en: 'Order status',
  espera_vivo: 'En vivo',
  espera_titulo: 'Pedidos en preparación',
  espera_titulo_en: 'Orders in progress',
  espera_preparando: 'En preparación',
  espera_preparando_en: 'Preparing',
  espera_cola: 'Pendiente de preparar',
  espera_cola_en: 'Pending',
  espera_total_cola: 'Pendientes de preparar',
  espera_vacio: 'No hay pedidos en preparación',
  espera_vacio_en: 'No orders in progress',
  espera_toca: 'Toca para ordenar',
  espera_toca_en: 'Touch to order'
});

registrarTextos('en', {
  bienvenida: 'Welcome to',
  titulo_portada: 'Discover our menu',
  comenzar: 'Start',
  ayuda_portada: 'Tap the screen to explore',
  idioma_es: 'ESP',
  idioma_en: 'ENG',
  idioma_etiqueta: 'Language',
  error_config_titulo: 'This kiosk is not set up',
  error_config_detalle: 'Please let a team member know.',
  ident_titulo_1: 'Please,',
  ident_titulo_2: 'enter your details',
  campo_edificio: 'Building',
  campo_habitacion: 'Room',
  campo_nombre: 'Confirm your name',
  reserva_a_nombre: 'Booked under',
  continuar: 'Continue',
  verificando: 'Checking…',
  verificando_lento: 'This may take a few seconds…',
  no_soy_yo: "That's not me",
  teclado_borrar: 'Delete',
  teclado_listo: 'Done',
  err_no_coincide: "Building and room don't match. Please check your details and try again.",
  err_bloqueado: 'Too many attempts. Please wait a minute and try again.',
  err_red: "We couldn't connect. Please try again.",
  err_general: 'Something went wrong. Please let a team member know.',
  volver: 'Back',
  menu_titulo: 'Menu',
  menu_cargando: 'Preparing the menu…',
  menu_error: "We couldn't load the menu. Please try again.",
  reintentar: 'Try again',
  agotado: 'Sold out',
  agregar: 'Add',
  orden_aria: 'My order',
  aviso_max_producto: "You've reached the maximum for this dish.",
  aviso_max_total: "You've reached the maximum items per order.",
  ordenar: 'Order',
  ver_detalle: 'View details for',
  aviso_agregado: 'added to your order',
  menu_lento: 'This is taking longer than usual. Please wait…',
  aviso_agotado: 'This dish is sold out for now.',
  orden_titulo: 'Confirm your order:',
  orden_producto: 'Product',
  orden_cantidad: 'Quantity',
  orden_vacia: 'Your order is empty.',
  orden_quitar: 'Remove',
  orden_cantidad_aria: 'Quantity of',
  aviso_max_lineas: "You've reached the maximum number of different dishes per order.",
  enviando: 'Sending…',
  pedido_lento: 'This is taking a little while. Your order is still being processed, please wait.',
  pedido_stock: 'We adjusted your order due to availability:',
  pedido_stock_reintento: 'The availability of some dishes changed. Please try again.',
  pedido_huesped: "We couldn't verify your room. Please let a team member know.",
  pedido_rate: 'There are many requests. Please wait a moment and try again.',
  ticket_titulo_1: 'Your order',
  ticket_titulo_2: 'number is:',
  ticket_mensaje: 'Please check the “Order status” screen to find out when it is ready.',
  ticket_gracias: 'Thank you!',
  ticket_finalizar: 'Finish order',
  inactividad_titulo: 'Are you still there?',
  inactividad_pedido: 'Your order will be cancelled in',
  inactividad_sesion: 'The session will close in',
  inactividad_segundos: 'seconds',
  inactividad_seguir: 'Stay here'
});